### ISSUE TITLE
Add enter stroke to end of search term

### ISSUE THREAD

**Issue by Mudartastisch** [Nekolike/Mappy#14]
In the current version, when you use the ctrl+scroll function right after pressing a keyword, you are still in the search window and change the typing position. 
Sending an enter stroke after the keyword would resolve this issue, giving a noticeable QoL improvement.

**Comment by Nekolike** [comment]
Great catch, I never would've caught that. Added the enter stroke which fixed that problem, thank you for your help!
As a nice little side note, the enter stroke also prevents random windows in PoE from popping up when hitting a button while not at stash since the enter will just open the chat window as the last command.
For the sake of documentation I will add to this comment that the problem was associated with the PoE Trademacro.
